variable "project_name" {}
variable "vpc_id" {}
variable "subnet_private_id" {}
variable "image_id" {}
variable "instance_type" {}
variable "efs_id" {}
variable "cidr_block_all" {}
variable "lb_tg_arn" {}
variable "iam_policy_arn_ec2" {}
variable "sg_lb_id" {}
variable "key_name" {}